### 服务器配置
server:
  port: 8080
  servlet:
    context-path: /admin

### prod项目配置
project:
  captcha-open: false                         #是否开启登录验证码
  shiro:
    remember-me-timeout: 7                    #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 1800              #Session会话超时时间，默认30分钟（秒）
  upload:
#    file-path: E:/Work                            #文件上传路径，默认在项目根目录upload下
    static-path: /xibian                  #上传文件静态访问路径/upload/**
  ke-url: http://ke.51yujianni.com           #领课url


### spring配置
spring:
## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xibian-mysql:3306/xibian?useSSL=false&characterEncoding=utf-8
    username: xibian
    password: xibian123456

## jpa配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.chenwt.common.mysql.MySQLDialectUTF8
      hibernate.format_sql: false
    open-in-view: true
